#
# Usual commands 
#

pull :
#	update from the repository
	cd .. ; git pull

push :
#	commit onto the repository
	cd .. ; git commit -a -m 'commited from makefile' ; git push


publish :
#	publish on the web site
	./publish.sh

clean :
#	clean local files
	./clean.sh
	cd .. ; git status


#install :
# In the parent directory we had to run : git clone git@github.com:guillaumematheron/carpasinivores
